/*
 * This source file was generated by the Gradle 'init' task
 */
package compiler.main;

import java.io.IOException;
import java.nio.file.Files;
import java.nio.file.Path;

import com.google.gson.*;

import compiler.error.ErrorList;
import compiler.lexer.Lexer;
import compiler.parser.Parser;

public class App {
    public static String readCode() {
        try {
            return Files.readString(Path.of("src/main/resources/code.macs"));
        } catch (IOException e) {
            System.err.printf("Error reading code file: %s\n", e.getMessage());
            System.exit(1);
            return null;
        }
    }

    public static void main(String[] args) {
        String code = readCode();
        try {
            var tokens = Lexer.tokenize(code);
            var ast = Parser.parse(tokens);

            Gson gson = new GsonBuilder().setPrettyPrinting().create();
            JsonElement je = JsonParser.parseString(ast.toString());
            System.out.println(gson.toJson(je));
        } catch (ErrorList errors) {
            System.err.println("Errors found during parsing:");
            errors.printWithSource(code);
            System.exit(1);
        }
    }
}
